# blacklisted people here
blacklisted_usernames = (
    "adawow_io",
    "LacedWhales",
    "Nathan_Combs_",
    "YoonaADA",
    "sangeyvang",
    "ChainEXIO",
    "AdaDarkPool",
    "CardanoPriceUpdates",
    "MBrae3",
    "BalanceOt",
    "LacedWhales",
)

# hashtags to blacklist
blacklisted_hashtags = (
    # "RT @",
    "info:",
    "moonpump",
    "Whale",
    "Output:",
    "DOGE",
    "#CardaxDEX",
    "coingecko",
    "#LUNA",
    "$LUNA",
    "price:",
    "in the past 24 hours",
    "the current price",
    "an expert!",
    "coinbase.com/join/",
    "#RETWEET",
    "retweet",
    "GIVEAWAY",
    "giveaway",
    "tag two friends",
    "TAG 2 FRIENDS",
    "Follow Me",
    "TAG 3 FRIENDS",
    "#CryptoTrading",
    "$HEX",
    "$hex",
    "#HEX",
    "#hex",
    "$FANC",
    "#FANC",
    "Binance Coin",
    "Tether",
    "Ethereum",
    "#XRP",
    "#xrp",
    "$xrp",
    "#dogecoins",
    "#ethereum",
    "#eth",
    "$eth",
    "#GRT",
    "#ETH",
    "$ETH",
    "#bnb",
    "#Telcoin",
    "#kishu",
    "#Musk",
    "#cancer",
    "#AMC",
    "Follow",
    "Daily Stats",
    "Follow+Like+Retweet",
    "Tag",
    "#Airdrop",
    "Airdrop",
    "#CRZ",
    "#BSC",
    "BSC",
    "$BSC",
    "#bsc",
    "$SHIB",
    "#VET",
    "$bsc",
    "#IOST",
    "#BTT",
    "#SUSHI",
    "#Shib",
    "#SHIB",
    "#shib",
    "#Binance",
    "#Doge",
    "Doge",
    "doge",
    "#UNI",
    "#XMR",
    "#THETA",
    "#TFUEL",
    "#BNB",
    "#bnb",
    "ETH:",
    "#DEX",
    "#LINK",
    "#disabled",
    "#IRIS",
    "#ORN",
    "#TRX",
    "#DENT",
    "#DOGE",
    "#doge",
    "#CAKE",
)
